services:
  mysql:
    image: mysql:8
    restart: always
    env_file:
      - .env.docker
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    volumes:
      - mysql-data:/var/lib/mysql
      - /c/banco/banco.sql:/docker-entrypoint-initdb.d/banco.sql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - app-network

  backend:
    build: ./backend
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env.docker
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      DB_RETRY_LIMIT: ${DB_RETRY_LIMIT}
      DB_RETRY_DELAY: ${DB_RETRY_DELAY}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
    restart: on-failure
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend-app
    restart: unless-stopped
    expose:
      - "5173"
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV}
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
