#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

cd frontend || exit 1

# Roda lint primeiro, se falhar, para o commit
npm run lint || exit 1

# Se lint passou, roda os testes, se falhar, para o commit
npm run test || exit 1

echo "✅ Lint e testes passaram. Commit liberado!"
